# Generated by Django 4.2.9 on 2024-03-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='orderd_date',
            new_name='ordered_date',
        ),
    ]
